function alaaplot(y,ym);

r = y-ym;

figure
subplot(211); 
plot(y,'b','LineWidth',2,...
             'MarkerEdgeColor','k',...
             'MarkerFaceColor','g',...
             'MarkerSize',2); hold on; grid;
hold on; plot(ym,'r-.','LineWidth',2,...
             'MarkerEdgeColor','k',...
             'MarkerFaceColor','g',...
             'MarkerSize',2);
xlabel('{\bf Number of Samples}');
legend('{\bf Observed}','{\bf Predicted}');

subplot(212); plot(r,'LineWidth',2,...
             'MarkerEdgeColor','k',...
             'MarkerFaceColor','g',...
             'MarkerSize',2);
title('{\bf Error Difference}'); grid;
xlabel('{\bf Number of Samples}');
